### ISSUE TITLE
sqlite3.OperationalError: no such table: user on login

### ISSUE THREAD

**Issue by damian0604** [ccs-amsterdam/amcat4#15]
Hi,

I just installed amcat4 as well as amcat4client on a fresh server. However, when I try to log on via the JS client, nothing happens, and the server backend shows that there seems to be a user table missing `sqlite3.OperationalError: no such table: user` (full log below). I guess this table should be created on the first run automatically? (and is there a quick fix?)
Thanks!

```
damian@tux01ascor:/opt/amcat4$ /usr/local/bin/uwsgi --ini /opt/amcat4/amcat4-uswgi.ini
[uWSGI] getting INI configuration from /opt/amcat4/amcat4-uswgi.ini
*** Starting uWSGI 2.0.20 (64bit) on [Wed Oct 13 08:23:11 2021] ***
compiled with version: 9.3.0 on 13 October 2021 08:03:07
os: Linux-5.4.0-88-generic #99-Ubuntu SMP Thu Sep 23 17:29:00 UTC 2021
nodename: tux01ascor
machine: x86_64
clock source: unix
detected number of CPU cores: 24
current working directory: /opt/amcat4
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
your processes number limit is 513470
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /tmp/amcat4.socket fd 3
Python version: 3.8.10 (default, Sep 28 2021, 16:10:42)  [GCC 9.3.0]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x55d7c47b5900
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 437520 bytes (427 KB) for 5 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x55d7c47b5900 pid: 8083 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 8083)
spawned uWSGI worker 1 (pid: 8085, cores: 1)
spawned uWSGI worker 2 (pid: 8086, cores: 1)
spawned uWSGI worker 3 (pid: 8087, cores: 1)
spawned uWSGI worker 4 (pid: 8088, cores: 1)
spawned uWSGI worker 5 (pid: 8089, cores: 1)
ERROR:amcat4.api:Exception on /auth/token/ [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 3144, in execute_sql
    cursor.execute(sql, params or ())
sqlite3.OperationalError: no such table: user

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.8/dist-packages/flask_httpauth.py", line 389, in decorated
    return selected_auth.login_required(role=role,
  File "/usr/local/lib/python3.8/dist-packages/flask_httpauth.py", line 161, in decorated
    user = self.authenticate(auth, password)
  File "/usr/local/lib/python3.8/dist-packages/flask_httpauth.py", line 238, in authenticate
    return self.verify_password_callback(username, client_password)
  File "/opt/amcat4/./amcat4/api/common.py", line 21, in verify_password
    g.current_user = auth.verify_user(username, password)
  File "/opt/amcat4/./amcat4/auth.py", line 83, in verify_user
    user = User.get(User.email == email)
  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 6438, in get
    return sq.get()
  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 6884, in get
    return clone.execute(database)[0]
  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 1907, in inner
    return method(self, database, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 1978, in execute
    return self._execute(database)
  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 2150, in _execute
    cursor = database.execute(self)
  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 3157, in execute
    return self.execute_sql(sql, params, commit=commit)
  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 3151, in execute_sql
    self.commit()
  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 2917, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 190, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 3144, in execute_sql
    cursor.execute(sql, params or ())
peewee.OperationalError: no such table: user
[pid: 8089|app: 0|req: 1/1] 145.92.75.158 () {52 vars in 795 bytes} [Wed Oct 13 08:26:06 2021] GET /amcat4server/auth/token/ => generated 290 bytes in 14 msecs (HTTP/1.1 500) 3 headers in 131 bytes (1 switches on core 0)
ERROR:amcat4.api:Exception on /auth/token/ [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 3144, in execute_sql
    cursor.execute(sql, params or ())
sqlite3.OperationalError: no such table: user

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.8/dist-packages/flask_httpauth.py", line 389, in decorated
    return selected_auth.login_required(role=role,
  File "/usr/local/lib/python3.8/dist-packages/flask_httpauth.py", line 161, in decorated
    user = self.authenticate(auth, password)
  File "/usr/local/lib/python3.8/dist-packages/flask_httpauth.py", line 238, in authenticate
    return self.verify_password_callback(username, client_password)
  File "/opt/amcat4/./amcat4/api/common.py", line 21, in verify_password
    g.current_user = auth.verify_user(username, password)
  File "/opt/amcat4/./amcat4/auth.py", line 83, in verify_user
    user = User.get(User.email == email)
  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 6438, in get
    return sq.get()
  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 6884, in get
    return clone.execute(database)[0]
  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 1907, in inner
    return method(self, database, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 1978, in execute
    return self._execute(database)
  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 2150, in _execute
    cursor = database.execute(self)
  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 3157, in execute
    return self.execute_sql(sql, params, commit=commit)
  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 3151, in execute_sql
    self.commit()
  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 2917, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 190, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 3144, in execute_sql
    cursor.execute(sql, params or ())
peewee.OperationalError: no such table: user
[pid: 8089|app: 0|req: 2/2] 145.92.75.158 () {52 vars in 795 bytes} [Wed Oct 13 08:26:45 2021] GET /amcat4server/auth/token/ => generated 290 bytes in 3 msecs (HTTP/1.1 500) 3 headers in 131 bytes (1 switches on core 0)
c^CSIGINT/SIGTERM received...killing workers...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
worker 5 buried after 1 seconds
goodbye to uWSGI.
VACUUM: unix socket /tmp/amcat4.socket removed.
```

**Comment by vanatteveldt** [comment]
We removed the whole database so I'm guessing this must be fixed :D
