### ISSUE TITLE
Uploading Documents with array of `object` as property returns KeyError 'type'

### ISSUE THREAD

**Issue by PeterWalchhofer** [ccs-amsterdam/amcat4#36]
Dear Maintainers,

When storing documents with a property of type 'object' I ran into an error.

Steps to reproduce:

```
amcat.create_index("speeches_ger4")
# does not change outcome:
# amcat.set_fields("speeches_ger4", {"term_tfidf": "object"})      
a = {
    "title": "Hallo du", 
    "date": "2021-01-01", 
    "text": "Hallo du, wie geht es dir?", 
    "term_tfidf": [
        {"term": "hallo",  "value": 0.2},
         {"term": "du", "value": 0.3}
     ]
}
amcat.upload_documents("speeches_ger4", [a])

# Also amcat.query not working
amcat.get_fields("speeches_ger4")
```
This returns the following error (on the amcat4 instance, the client just returns HTTP 500).
```

amcat4        | INFO:     172.26.0.5:34852 - "GET /index/speeches_ger4/fields HTTP/1.0" 500 Internal Server Error
amcat4        | ERROR:    Exception in ASGI application
amcat4        | Traceback (most recent call last):
amcat4        |   File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi
amcat4        |     result = await app(  # type: ignore[func-returns-value]
amcat4        |   File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
amcat4        |     return await self.app(scope, receive, send)
amcat4        |   File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 271, in __call__
amcat4        |     await super().__call__(scope, receive, send)
amcat4        |   File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 118, in __call__
amcat4        |     await self.middleware_stack(scope, receive, send)
amcat4        |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
amcat4        |     raise exc
amcat4        |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
amcat4        |     await self.app(scope, receive, _send)
amcat4        |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 84, in __call__
amcat4        |     await self.app(scope, receive, send)
amcat4        |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
amcat4        |     raise exc
amcat4        |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
amcat4        |     await self.app(scope, receive, sender)
amcat4        |   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
amcat4        |     raise e
amcat4        |   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
amcat4        |     await self.app(scope, receive, send)
amcat4        |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 706, in __call__
amcat4        |     await route.handle(scope, receive, send)
amcat4        |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
amcat4        |     await self.app(scope, receive, send)
amcat4        |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
amcat4        |     response = await func(request)
amcat4        |   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 237, in app
amcat4        |     raw_response = await run_endpoint_function(
amcat4        |   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 165, in run_endpoint_function
amcat4        |     return await run_in_threadpool(dependant.call, **values)
amcat4        |   File "/usr/local/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
amcat4        |     return await anyio.to_thread.run_sync(func, *args)
amcat4        |   File "/usr/local/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
amcat4        |     return await get_asynclib().run_sync_in_worker_thread(
amcat4        |   File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
amcat4        |     return await future
amcat4        |   File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
amcat4        |     result = context.run(func, *args)
amcat4        |   File "/usr/local/lib/python3.10/site-packages/amcat4/api/index.py", line 182, in get_fields
amcat4        |     return elastic.get_fields(indices)
amcat4        |   File "/usr/local/lib/python3.10/site-packages/amcat4/elastic.py", line 252, in get_fields
amcat4        |     for f, ftype in get_index_fields(ix).items():
amcat4        |   File "/usr/local/lib/python3.10/site-packages/amcat4/elastic.py", line 236, in get_index_fields
amcat4        |     result = dict(_get_fields(index))
amcat4        |   File "/usr/local/lib/python3.10/site-packages/amcat4/elastic.py", line 211, in _get_fields
amcat4        |     t = dict(name=k, type=_get_type_from_property(v))
amcat4        |   File "/usr/local/lib/python3.10/site-packages/amcat4/elastic.py", line 205, in _get_type_from_property
amcat4        |     return properties['type']
amcat4        | KeyError: 'type'
```

When I query the elasticsearch instance with postman directly, I can see that there is no `type` property. I suspect that 'object' is the default type and therefore it is not being returned.

Here is the output of 
GET http://localhost:9200/speeches_ger4

```
{
    "speeches_ger4": {
        "aliases": {},
        "mappings": {
            "properties": {
                "date": {
                    "type": "date",
                    "format": "strict_date_optional_time"
                },
                "term_tfidf": {
                    "properties": {
                        "term": {
                            "type": "text",
                            "fields": {
                                "keyword": {
                                    "type": "keyword",
                                    "ignore_above": 256
                                }
                            }
                        },
                        "value": {
                            "type": "float"
                        }
                    }
                },
                "text": {
                    "type": "text"
                },
                "title": {
                    "type": "text"
                },
                "url": {
                    "type": "keyword",
                    "meta": {
                        "amcat4_type": "url"
                    }
                }
            }
        },
        "settings": {
            "index": {
                "routing": {
                    "allocation": {
                        "include": {
                            "_tier_preference": "data_content"
                        }
                    }
                },
                "number_of_shards": "1",
                "provided_name": "speeches_ger4",
                "creation_date": "1679334914957",
                "number_of_replicas": "1",
                "uuid": "u6kfwZbtSQSrMGJ9wz7Umw",
                "version": {
                    "created": "7170999"
                }
            }
        }
    }
}
```

As the document is persisted in elasticsearch accurately, I suspect that this an amcat4 problem.

**Comment by JBGruber** [comment]
Thanks @PeterWalchhofer for reporting and diagnosing this! I just fixed it based on your idea that "object" might be the default and isn't saved specifically.
