### ISSUE TITLE
Timeout error

### ISSUE THREAD

**Issue by PeterWalchhofer** [ccs-amsterdam/amcat4#39]
I sometimes get a timeout error and the upload stops when I use the Amcat4 client. I don't know what the reason is, because it happens quite randomly (e.g. depending on chunk_size after 13% or 20% of my documents). I think one could fix this in the Amcat-client by simply re-trying when ConnectionTimeout occurs, but unfortunately AmCAT just returns a 500 instead of forwarding the 408 from Elastic.

The Timeout error occurs only for some document collections, while it works for others. I assume that some collections have larger documents and that after 10k docs ES has to perform some garbage collection or indexing, which leads to a Timeout. I could replicate this on multiple computers with different specs, so I do not think it is a performance issue on my local machine.

Here are the logs from the client
```
AMCAT-Client
Traceback (most recent call last):
  File "/home/peter/anaconda3/envs/opted/lib/python3.9/site-packages/amcat4py/amcatclient.py", line 90, in _request
    r.raise_for_status()
  File "/home/peter/anaconda3/envs/opted/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://localhost/amcat/index/speeches_cz/documents

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/peter/uni/ParLawSpeechDashboard/preprocess_upload/preprocess.py", line 137, in <module>
    preprocess_and_upload()
  File "/home/peter/anaconda3/envs/opted/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/peter/anaconda3/envs/opted/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/peter/anaconda3/envs/opted/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/peter/anaconda3/envs/opted/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/peter/uni/ParLawSpeechDashboard/preprocess_upload/preprocess.py", line 133, in preprocess_and_upload
    amcat.upload_documents(index_name, speeches_tftidf, chunk_size=10000)
  File "/home/peter/anaconda3/envs/opted/lib/python3.9/site-packages/amcat4py/amcatclient.py", line 334, in upload_documents
    self._post("documents", index=index, json=body)
  File "/home/peter/anaconda3/envs/opted/lib/python3.9/site-packages/amcat4py/amcatclient.py", line 106, in _post
    return self._request("post", url=self._url(url, index), data=data, headers=headers, ignore_status=ignore_status)
  File "/home/peter/anaconda3/envs/opted/lib/python3.9/site-packages/amcat4py/amcatclient.py", line 92, in _request
    raise AmcatError(e.response, e.request) from e
amcat4py.amcatclient.AmcatError: Error from server (500): Internal Server Error
 15%|███████████████████████                                

```

And here from the AmCAT instance 

```

2023-06-11 22:21:25 WARNING:elastic_transport.node_pool:Node <Urllib3HttpNode(http://elastic7:9200)> has failed for 1 times in a row, putting on 1 second timeout
2023-06-11 22:21:25 INFO:     172.26.0.5:57596 - "POST /index/speeches_cz/documents HTTP/1.0" 500 Internal Server Error
2023-06-11 22:21:25 ERROR:    Exception in ASGI application
2023-06-11 22:21:25 Traceback (most recent call last):
2023-06-11 22:21:25   File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 435, in run_asgi
2023-06-11 22:21:25     result = await app(  # type: ignore[func-returns-value]
2023-06-11 22:21:25   File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
2023-06-11 22:21:25     return await self.app(scope, receive, send)
2023-06-11 22:21:25   File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 276, in __call__
2023-06-11 22:21:25     await super().__call__(scope, receive, send)
2023-06-11 22:21:25   File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
2023-06-11 22:21:25     await self.middleware_stack(scope, receive, send)
2023-06-11 22:21:25   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
2023-06-11 22:21:25     raise exc
2023-06-11 22:21:25   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
2023-06-11 22:21:25     await self.app(scope, receive, _send)
2023-06-11 22:21:25   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 84, in __call__
2023-06-11 22:21:25     await self.app(scope, receive, send)
2023-06-11 22:21:25   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
2023-06-11 22:21:25     raise exc
2023-06-11 22:21:25   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
2023-06-11 22:21:25     await self.app(scope, receive, sender)
2023-06-11 22:21:25   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
2023-06-11 22:21:25     raise e
2023-06-11 22:21:25   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
2023-06-11 22:21:25     await self.app(scope, receive, send)
2023-06-11 22:21:25   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
2023-06-11 22:21:25     await route.handle(scope, receive, send)
2023-06-11 22:21:25   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
2023-06-11 22:21:25     await self.app(scope, receive, send)
2023-06-11 22:21:25   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
2023-06-11 22:21:25     response = await func(request)
2023-06-11 22:21:25   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 237, in app
2023-06-11 22:21:25     raw_response = await run_endpoint_function(
2023-06-11 22:21:25   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 165, in run_endpoint_function
2023-06-11 22:21:25     return await run_in_threadpool(dependant.call, **values)
2023-06-11 22:21:25   File "/usr/local/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
2023-06-11 22:21:25     return await anyio.to_thread.run_sync(func, *args)
2023-06-11 22:21:25   File "/usr/local/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
2023-06-11 22:21:25     return await get_asynclib().run_sync_in_worker_thread(
2023-06-11 22:21:25   File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
2023-06-11 22:21:25     return await future
2023-06-11 22:21:25   File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
2023-06-11 22:21:25     result = context.run(func, *args)
2023-06-11 22:21:25   File "/usr/local/lib/python3.10/site-packages/amcat4/api/index.py", line 155, in upload_documents
2023-06-11 22:21:25     return elastic.upload_documents(ix, documents, columns)
2023-06-11 22:21:25   File "/usr/local/lib/python3.10/site-packages/amcat4/elastic.py", line 179, in upload_documents
2023-06-11 22:21:25     bulk(es(), actions)
2023-06-11 22:21:25   File "/usr/local/lib/python3.10/site-packages/elasticsearch/helpers/actions.py", line 521, in bulk
2023-06-11 22:21:25     for ok, item in streaming_bulk(
2023-06-11 22:21:25   File "/usr/local/lib/python3.10/site-packages/elasticsearch/helpers/actions.py", line 436, in streaming_bulk
2023-06-11 22:21:25     for data, (ok, info) in zip(
2023-06-11 22:21:25   File "/usr/local/lib/python3.10/site-packages/elasticsearch/helpers/actions.py", line 339, in _process_bulk_chunk
2023-06-11 22:21:25     resp = client.bulk(*args, operations=bulk_actions, **kwargs)  # type: ignore[arg-type]
2023-06-11 22:21:25   File "/usr/local/lib/python3.10/site-packages/elasticsearch/_sync/client/utils.py", line 414, in wrapped
2023-06-11 22:21:25     return api(*args, **kwargs)
2023-06-11 22:21:25   File "/usr/local/lib/python3.10/site-packages/elasticsearch/_sync/client/__init__.py", line 702, in bulk
2023-06-11 22:21:25     return self.perform_request(  # type: ignore[return-value]
2023-06-11 22:21:25   File "/usr/local/lib/python3.10/site-packages/elasticsearch/_sync/client/_base.py", line 285, in perform_request
2023-06-11 22:21:25     meta, resp_body = self.transport.perform_request(
2023-06-11 22:21:25   File "/usr/local/lib/python3.10/site-packages/elastic_transport/_transport.py", line 329, in perform_request
2023-06-11 22:21:25     meta, raw_data = node.perform_request(
2023-06-11 22:21:25   File "/usr/local/lib/python3.10/site-packages/elastic_transport/_node/_http_urllib3.py", line 199, in perform_request
2023-06-11 22:21:25     raise err from None
2023-06-11 22:21:25 elastic_transport.ConnectionTimeout: Connection timed out
```

**Comment by JBGruber** [comment]
Thanks for filing the issue! I've seen this before when uploading large document collections. In the elastic logs it will probably show you some out of memory error. I also assume this is because of garbage collection or actually because Elasticsearch might be indexing the new docs. The solution was to change or remove the memory limit for Elasticsearch in the [docker compose file](https://github.com/ccs-amsterdam/amcat4docker/blob/main/docker-compose.yml). It's this line:

```
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
```

It's in there because the JVM will reserve a large percentage of your memory, even when it doesn't need it, which was annoying during development. But feel free to increase the limit. I will add a note to the compose file.

**Comment by vanatteveldt** [comment]
Note that uploading in smaller batches could also help. Both the R and Python clients have a batch/chunk size parameter, which I think is default set to 100. If you have large documents, you could try setting it to e.g. 10 to see if it helps?

**Comment by mrwunderbar666** [comment]
Increasing the memory limit to 8GB seems to do the trick (on my machine)

```
      - "ES_JAVA_OPTS=-Xms8g -Xmx8g"
```

**Comment by PeterWalchhofer** [comment]
Thank you very much for the fast response! 
I could try it now and it worked :)
